import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

// Fuentes auto-hospedadas (mismas familias variables de Google Fonts, subset
// latin) para que el build no dependa de descargar de fonts.googleapis.com.
const robotoSlab = localFont({
  src: "./fonts/roboto-slab-latin.woff2",
  weight: "100 900",
  variable: "--font-serif",
});

const geistSans = localFont({
  src: "./fonts/geist-latin.woff2",
  weight: "100 900",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "./fonts/geist-mono-latin.woff2",
  weight: "100 900",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-serif", robotoSlab.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
